### ISSUE TITLE
Anki doesn't launch with this plugin installed

### ISSUE THREAD

**Issue by spertulo97** [JASchilz/AnkiSyncDuolingo#71]
I installed the plugin, but now Anki shows me this traceback when launching.
  File "/usr/share/anki/aqt/addons.py", line 80, in loadAddons
    __import__(dir)
  File "/home/sergio/.local/share/Anki2/addons21/557761805/__init__.py", line 1, in <module>
    from . import plugin
  File "/home/sergio/.local/share/Anki2/addons21/557761805/plugin.py", line 10, in <module>
    from anki.collection import Collection
ImportError: cannot import name 'Collection' from 'anki.collection' (/usr/share/anki/anki/collection.py)

The version of Anki is 2.1.15 (Qt5)
I use it on Ubuntu Mate 20.04

**Comment by JASchilz** [comment]
Hi Spertulo, sorry that the plugin has caused that difficulty! Here's what has happened:
  * The plugin only supports Anki version 2.1.50+
  * There was an older version of the plugin that supported earlier versions of Anki, but the changes required between the older and newer versions of Anki were too much to keep up both plugins, so only 2.1.50+ is supported.
  * Ankiweb makes it difficult to retire old versions of plugins. I won't elaborate on the details, but this is why Ankiweb claimed that this plugin had a version compatible with your Anki.

Based on your problem, I figured out a hacky way to retire the old version of this plugin, so now Ankiweb reports that this plugin is only compatible with version 2.1.50+ of Anki. This doesn't help you out specifically, but it will help keep other people from running into the same problem.

I'm not sure how to remove a plugin that is keeping Anki from starting: it might be possible by finding and deleting the plugin in `~/.local/share/Anki2/`. But I'm fairly confident that if you were to update Anki to a newer version like 2.1.40+ then you should be able to at least start Anki.

If you were to upgrade to 2.1.50+ and wanted to use this plugin, you would probably have to re-install it after upgrading to 2.1.50+, as the version of the plugin that you currently have installed is probably the 2.1.49- version of the plugin which no longer works with the latest changes that Duolingo has made to their code.

Let me know if you could use any further assistance!
